// <auto-generated />
using Husky.TwoFactor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Husky.TwoFactor.Data.Migrations
{
    [DbContext(typeof(TwoFactorDbContext))]
    partial class TwoFactorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Husky.TwoFactor.Data.TwoFactorCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .HasColumnType("varchar(8)");

                    b.Property<DateTime>("CreatedTime");

					b.Property<int>("ErrorTimes");

                    b.Property<bool>("IsUsed");

                    b.Property<string>("SentTo")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserIdString")
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.ToTable("TwoFactorCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
