// <auto-generated />
using Husky.Mail.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Husky.Mail.Data.Migrations
{
    [DbContext(typeof(MailDbContext))]
    partial class MailDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Husky.Mail.Data.MailRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body");

                    b.Property<string>("Cc")
                        .HasMaxLength(2000);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Exception")
                        .HasMaxLength(500);

                    b.Property<bool>("IsHtml");

                    b.Property<bool>("IsSuccessful");

                    b.Property<Guid?>("SmtpId");

                    b.Property<string>("Subject")
                        .HasMaxLength(200);

                    b.Property<string>("To")
                        .HasMaxLength(2000);

                    b.HasKey("Id");

                    b.HasIndex("SmtpId");

                    b.ToTable("MailRecords");
                });

            modelBuilder.Entity("Husky.Mail.Data.MailRecordAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("ContentStream");

                    b.Property<string>("ContentType")
                        .HasMaxLength(32);

                    b.Property<DateTime>("CreatedTime");

                    b.Property<int>("MailId");

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("MailId");

                    b.ToTable("MailRecordAttachments");
                });

            modelBuilder.Entity("Husky.Mail.Data.MailSmtpProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CredentialName")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool>("IsInUse");

                    b.Property<string>("PasswordEncrypted")
                        .HasColumnType("varchar(64)")
                        .HasMaxLength(64);

                    b.Property<int>("Port");

                    b.Property<string>("SenderDisplayName")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("SenderMailAddress")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("Ssl");

                    b.HasKey("Id");

                    b.ToTable("MailSmtpProviders");
                });

            modelBuilder.Entity("Husky.Mail.Data.MailRecord", b =>
                {
                    b.HasOne("Husky.Mail.Data.MailSmtpProvider", "Smtp")
                        .WithMany("SentMails")
                        .HasForeignKey("SmtpId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Husky.Mail.Data.MailRecordAttachment", b =>
                {
                    b.HasOne("Husky.Mail.Data.MailRecord", "Mail")
                        .WithMany("Attachments")
                        .HasForeignKey("MailId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
